spring:
  application:
    name=rental-company:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:db-rental-company
    driverClassName: org.h2.Driver
    username: ${H2_DB_USER}
    password: ${H2_DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  flyway:
    schemas: rentalcompany

server:
  port: 7772
